=== nascimentolh/L2J_BrUnity/dist/game/data/xsd/KrateisCube.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="arena" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="doorA">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="list" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="doorB">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="list" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="waitLocations">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="point" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="optional"/>
														<xs:attribute type="xs:int" name="y" use="optional"/>
														<xs:attribute type="xs:short" name="z" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="battleLocations">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="point" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="optional"/>
														<xs:attribute type="xs:int" name="y" use="optional"/>
														<xs:attribute type="xs:short" name="z" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="watcherLocations">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="point" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="optional"/>
														<xs:attribute type="xs:int" name="y" use="optional"/>
														<xs:attribute type="xs:short" name="z" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="buffs">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:short" name="id" use="optional"/>
														<xs:attribute type="xs:byte" name="level" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="rewards">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="item">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:short" name="id" use="optional"/>
														<xs:attribute type="xs:byte" name="amount" use="optional"/>
														<xs:attribute type="xs:string" name="useModifers" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="add_parameters">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="set" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="name" use="optional"/>
														<xs:attribute type="xs:short" name="value" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:byte" name="id" use="optional"/>
						<xs:attribute type="xs:short" name="manager" use="optional"/>
						<xs:attribute type="xs:byte" name="minLevel" use="optional"/>
						<xs:attribute type="xs:byte" name="maxLevel" use="optional"/>
						<xs:attribute type="xs:byte" name="minPlayers" use="optional"/>
						<xs:attribute type="xs:byte" name="maxPlayers" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nascimentolh/L2J_BrUnity/dist/game/data/KrateisCube.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/KrateisCube.xsd">
	<arena id="1" manager="32504" minLevel="70" maxLevel="75" minPlayers="2" maxPlayers="25">
		<doorA list="17150007,17150009,17150011,17150013,17150016,17150017,17150018,17150019,17150020,17150027,17150029,17150031,17150033,17150036,17150037,17150038,17150039,17150040,17150047,17150049,17150051,17150053,17150056,17150057,17150058,17150059,17150060,17150067,17150069,17150071,17150073,17150076,17150077,17150078,17150079,17150080,17150087,17150089,17150091,17150093" />
		<doorB list="17150008,17150010,17150012,17150014,17150021,17150022,17150023,17150024,17150025,17150028,17150030,17150032,17150034,17150041,17150042,17150043,17150044,17150045,17150048,17150050,17150052,17150054,17150061,17150062,17150063,17150064,17150065,17150068,17150070,17150072,17150074,17150081,17150082,17150083,17150084,17150085,17150088,17150090,17150092,17150094" />
		<waitLocations>
			<point x="-87247" y="-16391" z="-8320" />
			<point x="-87159" y="-16594" z="-8320" />
			<point x="-87203" y="-16491" z="-8320" />
			<point x="-87205" y="-16273" z="-8320" />
			<point x="-87237" y="-16159" z="-8320" />
		</waitLocations>
		<battleLocations>
			<point x="-86067" y="-20467" z="-8379" />
			<point x="-84068" y="-20462" z="-8379" />
			<point x="-82066" y="-20461" z="-8379" />
			<point x="-80064" y="-20465" z="-8375" />
			<point x="-78063" y="-20466" z="-8375" />
			<point x="-86067" y="-18461" z="-8375" />
			<point x="-84065" y="-18464" z="-8371" />
			<point x="-82065" y="-18461" z="-8371" />
			<point x="-80062" y="-18461" z="-8375" />
			<point x="-78071" y="-18466" z="-8379" />
			<point x="-86063" y="-16465" z="-8375" />
			<point x="-84071" y="-16461" z="-8367" />
			<point x="-82064" y="-16466" z="-8383" />
			<point x="-80064" y="-16461" z="-8387" />
			<point x="-78070" y="-16462" z="-8375" />
			<point x="-86064" y="-14461" z="-8375" />
			<point x="-84066" y="-14465" z="-8371" />
			<point x="-82066" y="-14462" z="-8387" />
			<point x="-80067" y="-14462" z="-8391" />
			<point x="-78065" y="-14463" z="-8379" />
			<point x="-86063" y="-12464" z="-8375" />
			<point x="-84066" y="-12462" z="-8387" />
			<point x="-82067" y="-12462" z="-8379" />
			<point x="-80069" y="-12465" z="-8375" />
			<point x="-78066" y="-12462" z="-8383" />
		</battleLocations>
		<watcherLocations>
			<point x="-85984" y="-20400" z="-8352" />
			<point x="-83984" y="-20400" z="-8352" />
			<point x="-81984" y="-20400" z="-8352" />
			<point x="-79984" y="-20400" z="-8352" />
			<point x="-77984" y="-20400" z="-8352" />
			<point x="-85984" y="-18400" z="-8352" />
			<point x="-83984" y="-18400" z="-8352" />
			<point x="-81984" y="-18400" z="-8352" />
			<point x="-79984" y="-18400" z="-8352" />
			<point x="-77984" y="-18400" z="-8352" />
			<point x="-85984" y="-16400" z="-8352" />
			<point x="-83984" y="-16400" z="-8352" />
			<point x="-81984" y="-16400" z="-8352" />
			<point x="-79984" y="-16400" z="-8352" />
			<point x="-77984" y="-16400" z="-8352" />
			<point x="-85984" y="-14400" z="-8352" />
			<point x="-83984" y="-14400" z="-8352" />
			<point x="-81984" y="-14400" z="-8352" />
			<point x="-79984" y="-14400" z="-8352" />
			<point x="-77984" y="-14400" z="-8352" />
			<point x="-85984" y="-12400" z="-8352" />
			<point x="-83984" y="-12400" z="-8352" />
			<point x="-81984" y="-12400" z="-8352" />
			<point x="-77984" y="-12400" z="-8352" />
		</watcherLocations>
		<buffs>
			<skill id="1086" level="2" />
			<skill id="1204" level="2" />
			<skill id="1059" level="3" />
			<skill id="1085" level="3" />
			<skill id="1078" level="6" />
			<skill id="1068" level="3" />
			<skill id="1240" level="3" />
			<skill id="1077" level="3" />
			<skill id="1242" level="3" />
			<skill id="1062" level="2" />
		</buffs>
		<rewards>
			<item id="13067" amount="1" useModifers="true" />
		</rewards>
		<add_parameters>
			<set name="minPoints" value="10" />
			<set name="pointPerPlayer" value="3" />
			<set name="pointPerMob" value="1" />
			<set name="expModifier" value="1800" />
			<set name="spModifier" value="180" />
			<set name="doorRotationTime" value="25" />
			<set name="watcherRotationTime" value="30" />
			<set name="respawnTime" value="10" />
		</add_parameters>
	</arena>
	<arena id="2" manager="32505" minLevel="76" maxLevel="79" minPlayers="2" maxPlayers="25">
		<doorA list="17170007,17170009,17170011,17170013,17170016,17170017,17170018,17170019,17170020,17170027,17170029,17170031,17170033,17170036,17170037,17170038,17170039,17170040,17170047,17170049,17170051,17170053,17170056,17170057,17170058,17170059,17170060,17170067,17170069,17170071,17170073,17170076,17170077,17170078,17170079,17170080,17170087,17170089,17170091,17170093" />
		<doorB list="17170008,17170010,17170012,17170014,17170021,17170022,17170023,17170024,17170025,17170028,17170030,17170032,17170034,17170041,17170042,17170043,17170044,17170045,17170048,17170050,17170052,17170054,17170061,17170062,17170063,17170064,17170065,17170068,17170070,17170072,17170074,17170081,17170082,17170083,17170084,17170085,17170088,17170090,17170092,17170094" />
		<waitLocations>
			<point x="-87015" y="-81808" z="-8352" />
			<point x="-87008" y="-81971" z="-8352" />
			<point x="-87006" y="-81637" z="-8352" />
			<point x="-87015" y="-81881" z="-8352" />
			<point x="-87014" y="-81725" z="-8352" />
		</waitLocations>
		<battleLocations>
			<point x="-85909" y="-85782" z="-8288" />
			<point x="-83893" y="-85798" z="-8288" />
			<point x="-81909" y="-85798" z="-8288" />
			<point x="-79909" y="-85798" z="-8288" />
			<point x="-77909" y="-85782" z="-8288" />
			<point x="-85909" y="-83798" z="-8288" />
			<point x="-83893" y="-83798" z="-8288" />
			<point x="-81909" y="-83798" z="-8288" />
			<point x="-79909" y="-83798" z="-8288" />
			<point x="-77909" y="-83798" z="-8288" />
			<point x="-85909" y="-81798" z="-8288" />
			<point x="-83909" y="-81798" z="-8288" />
			<point x="-81893" y="-81798" z="-8288" />
			<point x="-79909" y="-81798" z="-8288" />
			<point x="-77909" y="-81798" z="-8288" />
			<point x="-85909" y="-79798" z="-8288" />
			<point x="-83909" y="-79798" z="-8288" />
			<point x="-81893" y="-79814" z="-8288" />
			<point x="-79909" y="-79798" z="-8288" />
			<point x="-77909" y="-79798" z="-8288" />
			<point x="-85893" y="-77798" z="-8288" />
			<point x="-83909" y="-77798" z="-8288" />
			<point x="-81925" y="-77798" z="-8288" />
			<point x="-79909" y="-77798" z="-8288" />
			<point x="-77909" y="-77798" z="-8288" />
		</battleLocations>
		<watcherLocations>
			<point x="-85904" y="-85808" z="-8352" />
			<point x="-83904" y="-85808" z="-8352" />
			<point x="-81904" y="-85808" z="-8352" />
			<point x="-79904" y="-85808" z="-8352" />
			<point x="-77904" y="-85808" z="-8352" />
			<point x="-85904" y="-83808" z="-8352" />
			<point x="-83904" y="-83808" z="-8352" />
			<point x="-81904" y="-83808" z="-8352" />
			<point x="-79904" y="-83808" z="-8352" />
			<point x="-77904" y="-83808" z="-8352" />
			<point x="-85904" y="-81808" z="-8352" />
			<point x="-83904" y="-81808" z="-8352" />
			<point x="-81904" y="-81808" z="-8352" />
			<point x="-79904" y="-81808" z="-8352" />
			<point x="-77904" y="-81808" z="-8352" />
			<point x="-85904" y="-79808" z="-8352" />
			<point x="-83904" y="-79808" z="-8352" />
			<point x="-81904" y="-79808" z="-8352" />
			<point x="-79904" y="-79808" z="-8352" />
			<point x="-77904" y="-79808" z="-8352" />
			<point x="-85904" y="-77808" z="-8352" />
			<point x="-83904" y="-77808" z="-8352" />
			<point x="-81904" y="-77808" z="-8352" />
			<point x="-79904" y="-77808" z="-8352" />
			<point x="-77904" y="-77808" z="-8352" />
		</watcherLocations>
		<buffs>
			<skill id="1086" level="2" />
			<skill id="1204" level="2" />
			<skill id="1059" level="3" />
			<skill id="1085" level="3" />
			<skill id="1078" level="6" />
			<skill id="1068" level="3" />
			<skill id="1240" level="3" />
			<skill id="1077" level="3" />
			<skill id="1242" level="3" />
			<skill id="1062" level="2" />
		</buffs>
		<rewards>
			<item id="13067" amount="1" useModifers="true" />
		</rewards>
		<add_parameters>
			<set name="minPoints" value="10" />
			<set name="pointPerPlayer" value="3" />
			<set name="pointPerMob" value="1" />
			<set name="expModifier" value="2100" />
			<set name="spModifier" value="210" />
			<set name="doorRotationTime" value="25" />
			<set name="watcherRotationTime" value="30" />
			<set name="respawnTime" value="10" />
		</add_parameters>
	</arena>
	<arena id="3" manager="32506" minLevel="80" maxLevel="85" minPlayers="2" maxPlayers="25">
		<doorA list="18150207,18150209,18150211,18150213,18150216,18150217,18150218,18150219,18150220,18150227,18150229,18150231,18150233,18150236,18150237,18150238,18150239,18150240,18150247,18150249,18150251,18150253,18150256,18150257,18150258,18150259,18150260,18150267,18150269,18150271,18150273,18150276,18150277,18150278,18150279,18150280,18150287,18150289,18150291,18150293" />
		<doorB list="18150208,18150210,18150212,18150214,18150221,18150222,18150223,18150224,18150225,18150228,18150230,18150232,18150234,18150241,18150242,18150243,18150244,18150245,18150248,18150250,18150252,18150254,18150261,18150262,18150263,18150264,18150265,18150268,18150270,18150272,18150274,18150281,18150282,18150283,18150284,18150285,18150288,18150290,18150292,18150294" />
		<waitLocations>
			<point x="-54000" y="-83280" z="-8336" />
			<point x="-53808" y="-83200" z="-8336" />
			<point x="-54080" y="-82800" z="-8336" />
			<point x="-53824" y="-82752" z="-8336" />
			<point x="-53648" y="-83024" z="-8336" />
		</waitLocations>
		<battleLocations>
			<point x="-52748" y="-86920" z="-8292" />
			<point x="-50732" y="-86936" z="-8292" />
			<point x="-48748" y="-86936" z="-8292" />
			<point x="-46748" y="-86936" z="-8292" />
			<point x="-44748" y="-86920" z="-8292" />
